const products = [
    {
      id: "ShopLand49",
      image: "/public/mouse-1.jpg",
      name: "Wired RGB Mouse",
      description: "Wired RGB Mouse, Optical USB Computer Mouse, 1600 DPI Silent LED Mouse for Windows PC, Laptop, Desktop, Notebook",
      company: "Amazon",
      price: 400,
      MRP: 500,
      stock: 19,
      star: 5,
      category: "Mouse",
      featured: true,
      trending: false,
      reviews: 80
    },
    {
      id: "ShopLand60",
      image: "/public/laptop-6.jpg",
      name: "XPS Laptops",
      description: "Power your passions with premium, precision-crafted laptops with innovative features.",
      company: "xps",
      price: 3100,
      MRP: 33500,
      stock: 16,
      star: 4,
      category: "Laptop",
      featured: true,
      trending: false,
      reviews: 85
    },
    {
      id: "ShopLand41",
      image: "/public/printer-4.jpg",
      name: "Hp Printer",
      description: "We are instrumental in offering quality-approved Computer Printer. We provide the entire range at market leading prices and within the promised time - frame.",
      company: "HP",
      price: 27999,
      MRP: 29500,
      stock: 13,
      star: 4.5,
      category: "Printer",
      featured: true,
      trending: false,
      reviews: 129
    },
    {
      id: "ShopLand51",
      image: "/public/mouse-3.jpg",
      name: "Gaming Wireless Mouse GT",
      description: "(gadget dream)M6 7 color light gaming mouse-black/M133 Wireless Bluetooth-compatible Three-mode Transparent Mouse Rechargeable",
      company: "Daraz",
      price: 550,
      MRP: 600,
      stock: 15,
      star: 4,
      category: "Mouse",
      featured: true,
      trending: false,
      reviews: 52
    },
    {
      id: "ShopLand37",
      image: "/public/phone-2.jpg",
      name: "Walton NEXG",
      description: "Indulge yourself to a world of opportunities brought to you by WALTON smart phones. Feel free to choose from the wide range of cutting-edge innovations and features to meet your modern demands. With the latest Android operating systems paired with user-friendly mobile devices with elegant design and premium build quality, we are constantly striving in this ever-so-demanding race to bring nothing but the best to our users.",
      company: "Walton",
      price: 18900,
      MRP: 20500,
      stock: 19,
      star: 4.5,
      category: "Mobile",
      featured: true,
      trending: false,
      reviews: 172
    },
    {
        id: "ShopLand4",
        image: "/public/accessories-4.jpg",
        name: "Computer accessories",
        description:
          "Computer inkjet printer Any device added to a computer that performs an additional feature, but is not required. A good example of an accessory is the computer printer, which gives the computer the ability to print, but the computer would still work if it didn’t have the printer. Below, is a listing of computer accessories",
        company: "Poly",
        price: 800,
        MRP: 1000,
        stock: 4,
        star: 3.5,
        category: "Accessories",
        featured: false,
        trending: false,
        reviews: 43,
      },
      {
        id: "ShopLand31",
        image: "/public/phone-7.jpg",
        name: "iPhone 14 pro",
        description:
          "LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 2000 nits (HBM). 1290 x 2796 pixels, 19.5:9 ratio. 12MP | 4K@24/25/30/60fps, 1080p@25/30/60/120fps, gyro-EIS. Li-Ion 4323 mAh, non-removable (16.68 Wh) | 15W wireless (MagSafe) , 7.5W wireless (Qi)",
        company: "Apple",
        price: 173990,
        MRP: 175000,
        stock: 11,
        star: 5,
        category: "Mobile",
        featured: true,
        trending: false,
        reviews: 38,
      },
      {
        _id: "65bcce5f2357d02a99a709f0",
        id: "ShopLand35",
        image: "/public/phone-4.jpg",
        name: "Xiaomi 13T",
        description:
          "Xiaomi may use first and third-party cookies to maintain the essential functionality of our website and detect website performance to help us improve our website and online products and services, as well as improving your experience by providing personalized content and tailored ads.",
        company: "Xiaomi",
        price: 15900,
        MRP: 16500,
        stock: 15,
        star: 4.5,
        category: "Mobile",
        featured: false,
        trending: false,
        reviews: 27,
      },
      {
        _id: "65bcce5f2357d02a99a709ec",
        id: "ShopLand48",
        image: "/public/headphone-4.jpg",
        name: "Wireless earphones BW21 Fun TWS",
        description:
          "BOROFONE BW21 Fun TWS, BT v5.3 earphones, 25mAh single earphone battery for 3.5 hours of use, 120 hours of standby, 250mAh charging case",
        company: "Amazon",
        price: 900,
        MRP: 1000,
        stock: 15,
        star: 4,
        category: "Headphone",
        featured: true,
        trending: false,
        reviews: 28,
      },
      {
        _id: "65bcce5f2357d02a99a709c8",
        id: "ShopLand56",
        image: "/public/keyboard-3.jpg",
        name: "Thermaltake X1 RGB Keyboard",
        description:
          "Thermaltake TT Premium X1 RGB Cherry MX Blue Switch Mechanical Gaming Keyboard",
        company: "StartTech",
        price: 800,
        MRP: 950,
        stock: 11,
        star: 4,
        category: "Keyboard",
        featured: false,
        trending: true,
        reviews: 65,
      },
      {
        _id: "65bcce5f2357d02a99a709c9",
        id: "ShopLand61",
        image: "/public/desktop-7.jpg",
        name: "Gaming PC 16gb, 64gb",
        description:
          "ERA_Gaming Desktop DT05-0001in PCIntel® Core™ i7 -10th Generation Turbo processor. 3.0ghz 4MB Cache | MSI Pro1 MotherBoard | HyperX 16 GB DDR4-3200 MHz XMP RGB Heatsink RAM (2 x 8 GB) | 512 GB WD Black PCIe® NVMe™ TLC M.2 SSD + 1 TB 7200 rpm SATA HDD | NVIDIA® GeForce RTX™ (4GB GDDR5 dedicated) with LHR. | Pro Bornz Cabinet | Windows 10/11 Pro Single Language in S mode. - Complete 3YR Warranty",
        company: "xps",
        price: 8300,
        MRP: 85500,
        stock: 16,
        star: 5,
        category: "Computer",
        featured: false,
        trending: true,
        reviews: 43,
      },
      {
        _id: "65bcce5f2357d02a99a709cf",
        id: "ShopLand59",
        image: "/public/headphone-5.jpg",
        name: "EKSA E7000 Gaming Headphone",
        description:
          "EKSA E7000 Gaming Headphone Direwolf Wired Headset comes with Multi-platform compatibility, Innovative design, Superior Sound Quality and Noise Cancellation. Vibe Gaming is the authorized Distributor of EKSA products in Bangladesh. Get free shipping on orders over 2500 BDT from Vibe Gaming.",
        company: "Marshall",
        price: 1500,
        MRP: 1650,
        stock: 11,
        star: 5,
        category: "Headphone",
        featured: true,
        trending: true,
        reviews: 33,
      },
      {
        id: "ShopLand33",
        image: "/public/phone-6.jpg",
        name: "Pocco",
        description: "Dual SIM Unlocked Android 8.1 Smartphone with HD Full Screen, 1GB RAM, 8GB ROM - 6.3 Inch, Yellow",
        company: "Pocco",
        price: 17590,
        MRP: 18500,
        stock: 13,
        star: 4.5,
        category: "Mobile",
        featured: false,
        trending: false,
        reviews: 18
      },
      {
        id: "ShopLand47",
        image: "/public/headphone-3.jpg",
        name: "Wireless headphones BO12 Power",
        description: "BOROFONE BO12 Power wireless headphones, BT 5.0, 300mAh battery for 8 hours of calls and music, support BT and AUX playback modes.",
        company: "Amazon",
        price: 1200,
        MRP: 1300,
        stock: 10,
        star: 4,
        category: "Headphone",
        featured: false,
        trending: false,
        reviews: 19
      },
      {
        id: "ShopLand11",
        image: "/public/camera-6.jpg",
        name: "4k DSLR Camera",
        description: "DSLR cameras are taking off in bd, and it's not just the photography pros anymore. You've likely seen your friends grabbing DSLRs for stunning shots, and the best part is, they're budget-friendly now. But navigating the options can be a bit overwhelming with all the tech jargon and brands. Don't fret, though! We've got your back with a list of the most enticing and affordable DSLR cameras in Bangladesh. Capture those memories in style!",
        company: "Canon",
        price: 10000,
        MRP: 12500,
        stock: 10,
        star: 4,
        category: "Camera",
        featured: true,
        trending: false,
        reviews: 21
      },
      {
        id: "ShopLand19",
        image: "/public/laptop-1.webp",
        name: "HP Pavilion 13.3 FHD Laptop",
        description: "HP Pavilion 13.3 FHD Laptop, Intel Core i3, 8GB RAM, 128GB SSD",
        company: "HP",
        price: 81500,
        MRP: 85500,
        stock: 16,
        star: 5,
        category: "Laptop",
        featured: true,
        trending: false,
        reviews: 143
      },
      {
        id: "ShopLand10",
        image: "/public/camera-5.jpg",
        name: "Hand Camera",
        description: "Best travel camera for 2024: top choices for your adventures | TechRadar",
        company: "Canon",
        price: 8000,
        MRP: 9500,
        stock: 10,
        star: 4.5,
        category: "Camera",
        featured: false,
        trending: false,
        reviews: 52
      },
      {
        id: "ShopLand13",
        image: "/public/desktop-2.jpg",
        name: "iBUYPOWER Gaming PC- Ryzen 7",
        description: "iBUYPOWER Gaming PC- Ryzen 7, RTX 3060, 16GB RAM, 1TB SSD, Windows 11 Home",
        company: "AMD",
        price: 156000,
        MRP: 160000,
        stock: 16,
        star: 5,
        category: "Computer",
        featured: true,
        trending: false,
        reviews: 123
      },
      {
        id: "ShopLand6",
        image: "/public/camera-1.jpg",
        name: "Canon EOS 90D DSLR Camera",
        description: "The EOS 90D becomes Canon’s most powerful mid-range DSLR to date, inheriting the body, side-hinged screen, optical viewfinder and 45-point autofocus of the earlier 80D, while upgrading the sensor resolution to 32.5 Megapixels, offering uncropped 4k video at 25 or 30p, faster burst shooting of 10fps, and reinstating the AF joystick which went missing on the three previous models. As such there’s upgrades whether you shoot still photos, film video, or like most owners of this series, do both. The image quality has the potential to beat 24 Megapixel models, but not by a huge margin and crucially only when fitted with a quality lens. In terms of video it’s great to finally enjoy uncropped 4k with Dual Pixel AF on an EOS body, but while it resolves more detail than 1080, it’s not as good as 4k from the best of its rivals, most notably the Sony A6400 and Fujifilm X-T30 and like other recent Canon cameras, there’s no sign of 24p either. More than making up for the restrictions for most people though is the sheer confidence with which Dual Pixel AF can keep a subject in focus.",
        company: "Canon",
        price: 9000,
        MRP: 10000,
        stock: 13,
        star: 4.5,
        category: "Camera",
        featured: false,
        trending: false,
        reviews: 21
      },
      {
        id: "ShopLand29",
        image: "/public/monitor-6.webp",
        name: "AMD Gaming Monitor",
        description: "Whether you're a PC or console gamer, using the best gaming monitor can make an incredible difference. Traditionally, monitors are something you'd find within an office or sitting atop your at-home computer setup. Now, they serve as immersive portals to our favorite gaming realms, and while many players will still choose to kick back and use a TV in the living room, using a desktop display is no longer just for those of your that wield a keyboard and mouse.",
        company: "AMD",
        price: 19500,
        MRP: 20000,
        stock: 10,
        star: 4.5,
        category: "Monitor",
        featured: true,
        trending: false,
        reviews: 20
      },
      {
        id: "ShopLand7",
        image: "/public/camera-2.jpg",
        name: "LEQTRONIQ 4K HD Auto Focus Camera",
        description: "LEQTRONIQ 4K HD Auto Focus Camera with 48MP 30FPS 18X Digital Zoom, Red. Leqtroniq 4K HD Auto Focus Camera with 48MP 60FPS 30X Digital Zoom; Camcorder .(Amateur Purpose)",
        company: "Canon",
        price: 26500,
        MRP: 29000,
        stock: 23,
        star: 5,
        category: "Camera",
        featured: true,
        trending: false,
        reviews: 99
      },
      {
        id: "ShopLand24",
        image: "/public/monitor-1.jpg",
        name: "Pixio PX277 Gaming monitor",
        description: "This 27-inch Pixio monitor is a great value even at its full list price, and at Amazon you can pick it up for even less. It features a QHD resolution along with AMD FreeSync and a speedy 144Hz refresh rate if you want to use it for gaming in addition to work. It's rated for an ample 350 nits of brightness. Just be sure to clip the coupon to get the full deal.",
        company: "Pixio",
        price: 17500,
        MRP: 19000,
        stock: 19,
        star: 5,
        category: "Monitor",
        featured: true,
        trending: false,
        reviews: 163
      },
      {
        id: "ShopLand43",
        image: "/public/watch-1.jpg",
        name: "Amazfit",
        description: "Kids Smart Watch with Camera, Games, Pedometer, Video & Music Player, Flashlights, Alarm Clock - Age 4-12",
        company: "Quartz",
        price: 4385,
        MRP: 4500,
        stock: 6,
        star: 5,
        category: "Watch",
        featured: true,
        trending: false,
        reviews: 131
      },
      {
        id: "ShopLand2",
        image: "/public/accessories-2.webp",
        name: "Laptop accessories",
        description: "9 essential back-to-school laptop accessories for under $100",
        company: "Apple",
        price: 70000,
        MRP: 82000,
        stock: 6,
        star: 5,
        category: "Accessories",
        featured: true,
        trending: false,
        reviews: 134
      },
      {
        id: "ShopLand3",
        image: "/public/accessories-3.jpg",
        name: "Laptop accessories",
        description: "So, you’ve got your college kid a brand new laptop, and they’re all set to conquer the academic world. Well, not so fast. As any computer user knows, plenty of extra accessories should complement a new PC to make it more useful, efficient, or just plain comfy. And since your student is going to be spending a lot of time on that computer, either at work or play, it’s a good idea to make sure they’re well-equipped to use it to the fullest.",
        company: "Asus",
        price: 35000,
        MRP: 42000,
        stock: 3,
        star: 4,
        category: "Accessories",
        featured: true,
        trending: false,
        reviews: 152
      },
      {
        id: "ShopLand1",
        image: "/public/accessories-1.jpg",
        name: "Laptop accessories",
        description: "WIWU GENIUS COMBO SET BAG WITH MOUSE AND MOUSE PAD FOR 14 LAPTOP/ULTRABOOK - BLACK",
        company: "Apple",
        price: 45000,
        MRP: 55000,
        stock: 10,
        star: 4.5,
        category: "Accessories",
        featured: false,
        trending: false,
        reviews: 23
      },
      {
        id: "ShopLand16",
        image: "/public/desktop-5.jpg",
        name: "Gaming Desktop, Intel Core I7",
        description: "STGAubron Gaming Desktop PC Computer, Intel Core I7 3.4 GHz up to 3.9 GHz, Radeon RX 580 8G GDDR5, 16G RAM, 512G SSD, WiFi, Bluetooth 5.0, RGB Fanx6, RGB Keyboard&Mouse&Mouse Pad, RGB BT Sound Bar, W10H64",
        company: "Intel",
        price: 95500,
        MRP: 100000,
        stock: 15,
        star: 4.5,
        category: "Computer",
        featured: true,
        trending: false,
        reviews: 41
      },
      {
        id: "ShopLand5",
        image: "/public/accessories-5.jpg",
        name: "Laptop accessories",
        description: "It is a known fact that no gadget, may it be inferior or superior comes with everything you need right in the box. It is important to choose the right gear whether you are buying the laptop or a computer as a gift or even for yourself.",
        company: "HP",
        price: 1350,
        MRP: 1400,
        stock: 9,
        star: 5,
        category: "Accessories",
        featured: false,
        trending: false,
        reviews: 91
      },
      {
        id: "ShopLand42",
        image: "/public/printer-2.jpg",
        name: "Epson EcoTank L5590",
        description: "C11CK57502 | Epson EcoTank L5590 Ink Tank Printer | Ink Tank System Printers | Epson Malaysia",
        company: "Epson",
        price: 16500,
        MRP: 18500,
        stock: 8,
        star: 4,
        category: "Printer",
        featured: false,
        trending: false,
        reviews: 25
      },
      {
        id: "ShopLand58",
        image: "/public/keyboard-5.jpg",
        name: "HP 150 Wired Keyboard",
        description: "This chiclet-style keyboard is quick, comfy, and quite accurate. Just your type. Common controls are integrated into 12 shortcut combos with the Fn key—music, movies, volume, homepage, bookmarks, and email. Now that's a shortcut above",
        company: "HP",
        price: 2550,
        MRP: 1700,
        stock: 19,
        star: 5,
        category: "Keyboard",
        featured: false,
        trending: false,
        reviews: 39
      },
      {
        id: "ShopLand18",
        image: "/public/headphone-1.jpg",
        name: "Wireless On-Ear Headphones",
        description: "Marshall MAJOR IV Wireless On-Ear Headphones",
        company: "Marshall",
        price: 500,
        MRP: 650,
        stock: 10,
        star: 5,
        category: "Headphone",
        featured: true,
        trending: false,
        reviews: 91
      },
      {
        id: "ShopLand17",
        image: "/public/desktop-6.jpg",
        name: "Luxe Gaming PC - Intel Core i9-11900KF",
        description: "CYBERPOWERPC Luxe Gaming PC - Intel Core i9-11900KF, Nvidia RTX 4060 Ti 8GB, 32GB RAM, 1TB NVMe SSD, 650W 80+ PSU, Wi-Fi, Liquid Cooling",
        company: "Intel",
        price: 185590,
        MRP: 190500,
        stock: 18,
        star: 4.5,
        category: "Computer",
        featured: true,
        trending: false,
        reviews: 18
      },
      {
        id: "ShopLand20",
        image: "/public/laptop-2.webp",
        name: "Walton TAMARIND EX710G",
        description: "Walton TAMARIND EX710G 14-inch Full HD Display Core i7 10th Gen 8GB RAM 512GB SSD Laptop",
        company: "Walton",
        price: 70800,
        MRP: 75500,
        stock: 9,
        star: 4.5,
        category: "Laptop",
        featured: true,
        trending: false,
        reviews: 59
      },
      {
        _id: "65bcce5f2357d02a99a709e7",
        id: "ShopLand44",
        image: "/public/watch-2.jpg",
        name: "Amazfit Pop 2 Calling Smartwatch",
        description: "Music Control, Camera Control, Find Phone, Breath Training, 12/24-hour, Stopwatch, Clock, Weather Forecast, Date Display, Dial, Cloud Multi-Dial, Custom Dial, OTA Upgrade, Multi-Language UI Interface, Multi-Language, Data Storage, All-Day Data, Call Notification, Message Reminder, Alarm Reminder, Step Goal Completion Reminder, Binding Confirmation Reminder, Low Battery Reminder, Brightness Adjustment, Vibration Adjustment, Wear Monitoring, Lift Wrist to Wake Screen, Power Saving Mode, Smart DND, Quick Settings, Female Cycle, Voice Assistant",
        company: "Amazfit",
        price: 5490,
        MRP: 5700,
        stock: 13,
        star: 4.5,
        category: "Watch",
        featured: true,
        trending: false,
        reviews: 61
      },
      {
        _id: "65bcce5f2357d02a99a709ef",
        id: "ShopLand26",
        image: "/public/monitor-3.jpg",
        name: "Dell 32 Curved 4K UHD Monitor - S3221QS",
        description: "31.5 curved 4K UHD monitor that supports HDR content playback for a truly immersive entertainment experience.",
        company: "Dell",
        price: 13000,
        MRP: 14500,
        stock: 13,
        star: 3.5,
        category: "Monitor",
        featured: false,
        trending: false,
        reviews: 65
      },
      {
        _id: "65bcce5f2357d02a99a709bf",
        id: "ShopLand57",
        image: "/public/keyboard-4.jpg",
        name: "RGB Gaming Keyboard",
        description: "RGB Gaming Keyboard and Mouse-Light Up & LED Backlit Mechanical Keyboard & Mouse Combo-Rainbow Keyboard with 104 Keys- Gaming Mouse, for PS4, PS5, Xbox, PC, Laptop-Black",
        company: "Ubuy",
        price: 1350,
        MRP: 1400,
        stock: 19,
        star: 4,
        category: "Keyboard",
        featured: true,
        trending: false,
        reviews: 183
      },
      {
        _id: "65bcce5f2357d02a99a709c2",
        id: "ShopLand14",
        image: "/public/desktop-3.jpg",
        name: "Desktop PC Core i5 6th Gen 22",
        description: "Desktop PC comes with Intel core i5 6th generation processor, Intel chipset, Gigabyte GA-H110M-H motherboard, 8GB RAM, and 256GB SSD. The desktop computer included Xiaomi Redmi RMMNT215NF 21.45 FHD IPS monitor and USB keyboard, mouse.",
        company: "Intel",
        price: 25500,
        MRP: 28000,
        stock: 10,
        star: 3.5,
        category: "Computer",
        featured: true,
        trending: false,
        reviews: 184
      },
      {
        _id: "65bcce5f2357d02a99a709dd",
        id: "ShopLand27",
        image: "/public/monitor-4.jpg",
        name: "HP M24f 24 FHD IPS Monitor",
        description: "With the HP M24f 24 FHD IPS Monitor, of course! This amazing monitor is designed with IPS technology for 178 degrees ultra-wide viewing angles, 99% sRGB color gamut for color accuracy, and Freesync to keep your eyes up to speed with your imagination. Plus, the Eyesafe technology doesn't sacrifice color quality, so you can work comfortably for long periods of time. And because it's made with 85% recycled materials, you can feel good about using a sustainable product.",
        company: "HP",
        price: 14500,
        MRP: 15800,
        stock: 17,
        star: 4,
        category: "Monitor",
        featured: true,
        trending: false,
        reviews: 87
      },
      {
        id: "ShopLand9",
        image: "/public/camera-4.jpg",
        name: "Canon EOS R6 Mark II",
        description: "The Canon EOS R6 Mark II is our favorite full-frame camera for most people. It snaps attractive 24MP photos and has a class-leading autofocus system that smartly recognizes people, animals, and vehicles. With 12fps (mechanical) and 40fps (electronic shutter) bursts available, it's especially suitable for action shots, while stabilized 4K60 video should please filmmakers and vloggers.",
        company: "nikon",
        price: "10500",
        MRP: "11,500",
        stock: 10,
        star: 4,
        category: "Camera",
        featured: false,
        trending: false,
        reviews: 39
      },
      {
        id: "ShopLand21",
        image: "/public/laptop-3.jpg",
        name: "MacBook Alternatives | WIRED laptop",
        description: "The Swift 5 is incredibly thin and light, and it manages to have more ports than the Air, so you won't have to tote around a bunch of dongles and hubs just to download some photos from your SD card. It fares well in performance for the money, and it edges ahead of the Air in battery life.",
        company: "Apple",
        price: "82000",
        MRP: "85,500",
        stock: 19,
        star: 5,
        category: "Laptop",
        featured: false,
        trending: false,
        reviews: 83
      },
      {
        id: "ShopLand32",
        image: "/public/phone-8.jpg",
        name: "Samsung s24 Ultra",
        description: "Dual Sim, eSIM (Nano-SIM), (2 Nano-SIMs and eSIM, dual stand-by). HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100. 512GB Built-in, 12GB RAM. Dynamic AMOLED 2X Capacitive Touchscreen",
        company: "samsung",
        price: "18590",
        MRP: "20,000",
        stock: 17,
        star: 5,
        category: "Mobile",
        featured: true,
        trending: false,
        reviews: 48
      },
      {
        id: "ShopLand28",
        image: "/public/monitor-5.jpg",
        name: "HP 758st IPS monitor",
        description: "Whether you’re buying a first or second monitor for your desktop computer or buying a big screen to use with your laptop at home, a good monitor is a wise investment. There’s no single monitor that will work best for everyone, but our monitor guides cover all different sizes, uses, and prices, from basic, 24-inch budget models to big 4K screens to high-refresh-rate gaming monitors. Here we discuss the best ones you can buy as well as what you might need them for.",
        company: "hp",
        price: "18590",
        MRP: "19,900",
        stock: 15,
        star: 4.5,
        category: "Monitor",
        featured: false,
        trending: false,
        reviews: 74
      },
      {
        id: "ShopLand45",
        image: "/public/watch-3.jpg",
        name: "Smart Watch For Men",
        description: "Smart Watch For Men/Women Waterproof Smartwatch Bluetooth iPhone Samsung",
        company: "Amazon",
        price: "8490",
        MRP: "9,700",
        stock: 17,
        star: 4.5,
        category: "Watch",
        featured: false,
        trending: false,
        reviews: 52
      },
      {
        id: "ShopLand52",
        image: "/public/mouse-4.jpg",
        name: "T-Wolf V6 Gaming Design RGB Mouse",
        description: "Zymak Electronics, Shop No: 126, Ground Floor, Concord Arcadia Shopping Mall, Science Lab, Dhanmondi, Dhaka, Bangladesh",
        company: "Daraz",
        price: "450",
        MRP: "5,00",
        stock: "18",
        star: "5",
        category: "Mouse",
        featured: false,
        trending: true,
        reviews: "79"
      },
      {
        id: "ShopLand23",
        image: "/public/laptop-5.jpg",
        name: "Dell XPS 13",
        description: "CPU: Intel Core i7-1250U | RAM: 8GB DDR5 | Graphics: Intel Iris X3 | Storage: 512GB SSD | Display: 13.4-inch | Resolution: 1,920 x 1,200 | Refresh rate: 60Hz | Battery life: Up to 12 hours | Dimensions: 11.6 x 7.9 x 0.6 inches | Weight: 2.6 pounds",
        company: "Dell",
        price: "133500",
        MRP: "135,000",
        stock: "16",
        star: "3.5",
        category: "Laptop",
        featured: false,
        trending: false,
        reviews: "29"
      },
      {
        id: "ShopLand34",
        image: "/public/phone-3.jpg",
        name: "Walton NEXG N25",
        description: "Indulge yourself to a world of opportunities brought to you by WALTON smart phones. Feel free to choose from the wide range of cutting-edge innovations and features to meet your modern demands. With the latest Android operating systems paired with user-friendly mobile devices with elegant design and premium build quality, we are constantly striving in this ever-so-demanding race to bring nothing but the best to our users.",
        company: "Walton",
        price: "13000",
        MRP: "24,500",
        stock: "19",
        star: "4",
        category: "Mobile",
        featured: false,
        trending: false,
        reviews: "19"
      },
      {
        id: "ShopLand15",
        image: "/public/desktop-4.jpg",
        name: "Desktop PC Core i7 3rd Gen 22",
        description: "The lowest price of Desktop pc core i7 3rd gen 22 monitor with 8gb ram in Bangladesh is Tk-21,500/= only. Buy from Dhaka City at low price in Bdstall.",
        company: "Intel",
        price: "27990",
        MRP: "30,000",
        stock: "18",
        star: "4.5",
        category: "Computer",
        featured: true,
        trending: false,
        reviews: "96"
      },
      {
        id: "ShopLand36",
        image: "/public/phone-1.jpg",
        name: "T angxi",
        description: "T angxi Unlocked Smartphones, Mate40 Pro Dual SIM Unlocked Cell Phones Smart Phone, 5.45in HD Full Screen, 1GB RAM + 8GB ROM, 2MP + 5MP, Android 6.0, Face/Fingerprint Unlock, 2200mAh Battery(Green)",
        company: "T angxi",
        price: "89999",
        MRP: "102,500",
        stock: "14",
        star: "4.5",
        category: "Mobile",
        featured: true,
        trending: false,
        reviews: "98"
      },
      {
        id: "ShopLand38",
        image: "/public/phone-5.jpg",
        name: "Redmi Note 12 Pro+",
        description: "Redmi Note 12 Pro+ 5G is Xiaomi's latest mid-range smartphone offering in India. The top-of-the-line phone in the Note 12 series is a direct successor to the Redmi Note 11 Pro+ 5G (Review), which didn't quite pan out to be a segment leader as many would have hoped for, in our opinion. Xiaomi is now trying to fill the void with the Redmi Note 12 Pro+ 5G, with some segment-first hardware.",
        company: "Redmi",
        price: "27999",
        MRP: "29,500",
        stock: "23",
        star: "4.5",
        category: "Mobile",
        featured: false,
        trending: false,
        reviews: "103"
      },
      {
        id: "ShopLand54",
        image: "/public/keyboard-1.jpg",
        name: "Wireless gaming Keyboard",
        description: "Wireless gaming Keyboard and Mouse, Rainbow Backlit Rechargeable Keyboard Mouse with 3800mAh Battery Metal Panel, Removable Hand Rest Mechanical Feel Keyboard and 7 Color Gaming Mute Mouse for PC Gamers",
        company: "Amazon",
        price: "1900",
        MRP: "2,000",
        stock: "17",
        star: "4",
        category: "Keyboard",
        featured: true,
        trending: false,
        reviews: "105"
      },
      {
        id: "ShopLand62",
        image: "/public/laptop-7.jpg",
        name: "MacBook Pro overhaul",
        description: "Apple’s new 14- and 16-inch MacBook Pro with M1 Pro and M1 Max are faster and have longer battery lives than their predecessors, the company says. (Apple Inc.)",
        company: "xps",
        price: "19300",
        MRP: "199,500",
        stock: "16",
        star: "5",
        category: "Laptop",
        featured: false,
        trending: true,
        reviews: "54"
      },
      {
        id: "ShopLand40",
        image: "/public/printer-3.jpg",
        name: "Hp Printer",
        description: "The reliable, simple-to-operate HP OfficeJet Pro 9015e, an all-in-one color inkjet, is a good choice for most people who need to print regularly at home. It’s easy to set up and cheap to run, it works with all kinds of devices, and it produces beautiful prints, from tax forms to glossy photos.",
        company: "HP",
        price: "23999",
        MRP: "25,500",
        stock: "15",
        star: "5",
        category: "Printer",
        featured: false,
        trending: false,
        reviews: "32"
      },
      {
        id: "ShopLand22",
        image: "/public/laptop-4.jpg",
        name: "Samsung Galaxy Book Ion",
        description: "Samsung Galaxy Book Ion QLED display is gorgeous, too. It has a max brightness of 443 nits, making the colours appear incredibly vivid. Colour accuracy is excellent and the 1080p resolution makes this ultrabook perfect for streaming video",
        company: "Samsung",
        price: "35500",
        MRP: "37,800",
        stock: "13",
        star: "4.5",
        category: "Laptop",
        featured: true,
        trending: false,
        reviews: "47"
      },
      {
        id: "ShopLand39",
        image: "/public/printer-1.jpg",
        name: "Printer PIXMA E3470",
        description: "This Ink Efficient printer is designed to give you an affordable wireless printing experience at low running cost of up to 400 pages. Print, Scan, Copy. Print Speed (A4, ISO): up to 7.7 / 4 ipm (mono/colour). Wi-Fi, AirPrint, Mopria, Wireless Direct, Wireless PictBridge. Recommended Monthly Print Volume: 50 - 200 pages",
        company: "Canon",
        price: "15600",
        MRP: "17,500",
        stock: "21",
        star: "5",
        category: "Printer",
        featured: true,
        trending: false,
        reviews: "27"
      },
      {
        id: "ShopLand46",
        image: "/public/headphone-2.jpg",
        name: "Wired Gaming Headphones",
        description: "Amazon Basics Wired Over Ear Gaming Headphones mic for PC, Laptop | Static RGB | (Black)",
        company: "Amazon",
        price: "1500",
        MRP: "16,50",
        stock: "14",
        star: "5",
        category: "Headphone",
        featured: true,
        trending: false,
        reviews: "89"
      },
      {
        id: "ShopLand55",
        image: "/public/keyboard-2.jpg",
        name: "RK918 RGB Mechanical Keyboard",
        description: "RK918 Wired RGB Backlit Mechanical Gaming Keyboard with LED Surrounding Side Lamp",
        company: "Ubuy",
        price: "1190",
        MRP: "13,50",
        stock: "17",
        star: "4.5",
        category: "Keyboard",
        featured: false,
        trending: false,
        reviews: "65"
      },
      {
        id: "ShopLand50",
        image: "/public/mouse-2.jpg",
        name: "Logitech G203 Gaming Mouse",
        description: "Logitech G USB G G203 Wired Gaming Mouse, 8000 DPI, Rainbow Optical Effect LIGHTSYNC RGB, 6 Programmable Buttons, On-Board Memory, Screen Mapping, PC/Mac Computer and Laptop Compatible - Black",
        company: "Logitech",
        price: "800",
        MRP: "9,00",
        stock: "11",
        star: "4.5",
        category: "Mouse",
        featured: true,
        trending: false,
        reviews: "82"
      },
      {
        _id: { $oid: "65bcce5f2357d02a99a709d4" },
        id: "ShopLand12",
        image: "/public/desktop-1.webp",
        name: "The best Gaming PC",
        description: "The best gaming PCs are powerful enough to run even the most demanding video games well and do so in the biggest and most elegant design possible. While these machines are in some ways the epitome of what a PC can be, they often come with steep price tags. While the lofty costs you pay for a top-of-the-line gaming PC are nothing to shrug at, the benefits you reap are often worth the cost of entry.",
        company: "Apple",
        price: "120000",
        MRP: "129,000",
        stock: "30",
        star: "5",
        category: "Computer",
        featured: true,
        trending: false,
        reviews: "16"
      },
      {
        id: "ShopLand30",
        image: "/public/monitor-7.jpg",
        name: "HP monitor",
        description: "KOORUI Gaming Monitor, 24.5 Inch Computer Monitors Full HD (1920 x 1080), 1ms, VA, 2x HDMI (144Hz) & DisplayPort (170Hz), Adpitive Sync, sRGB 99%, VESA, Tilt Adjustable, Eye Care",
        company: "HP",
        price: 18990,
        MRP: 20000,
        stock: 19,
        star: 4.5,
        category: "Monitor",
        featured: false,
        trending: false,
        reviews: 27
      }
];
export default products;